#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.8
# from Racc grammer file "".
#

require 'racc/parser.rb'

  require 'ba_speak/lexer'
  require 'ba_speak/nodes'

module BaSpeak
  class Parser < Racc::Parser

module_eval(<<'...end parser.y/module_eval...', 'parser.y', 59)
  def parse(code, show_tokens=false)
    @tokens = Lexer.new.tokenize(code)
    puts @tokens.inspect if show_tokens
    do_parse
  end

  def next_token
    @tokens.shift
  end
...end parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
     3,     7,    13,    15,     7,     8,     3,     4,     3,    15,
    19,    13,    15,    19 ]

racc_action_check = [
     3,     3,     7,     7,    10,     4,     6,     1,     0,    11,
    15,    17,    18,    19 ]

racc_action_pointer = [
     6,     7,   nil,    -2,     5,   nil,     4,    -2,   nil,   nil,
     1,     4,   nil,   nil,   nil,     4,   nil,     7,     7,     7,
   nil,   nil,   nil ]

racc_action_default = [
    -1,   -20,    -2,    -3,   -20,    -4,    -5,    -7,    23,    -6,
    -8,   -10,   -11,   -14,   -15,   -20,    -9,   -12,   -16,   -18,
   -13,   -17,   -19 ]

racc_goto_table = [
    11,     6,    10,     2,    21,     1,     5,    12,    16,     9,
    20,    17,    18,   nil,   nil,   nil,    22 ]

racc_goto_check = [
     5,     3,     4,     2,     7,     1,     2,     6,     3,     2,
     5,     6,     8,   nil,   nil,   nil,     8 ]

racc_goto_pointer = [
   nil,     5,     3,    -2,    -5,    -7,     0,   -14,    -3 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    14,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  0, 8, :_reduce_1,
  1, 8, :_reduce_2,
  1, 9, :_reduce_3,
  2, 9, :_reduce_4,
  2, 9, :_reduce_5,
  3, 9, :_reduce_6,
  1, 10, :_reduce_7,
  2, 10, :_reduce_8,
  3, 10, :_reduce_9,
  1, 11, :_reduce_10,
  1, 11, :_reduce_11,
  2, 11, :_reduce_12,
  3, 11, :_reduce_13,
  1, 12, :_reduce_14,
  1, 13, :_reduce_15,
  2, 14, :_reduce_16,
  3, 14, :_reduce_17,
  1, 15, :_reduce_18,
  2, 15, :_reduce_19 ]

racc_reduce_n = 20

racc_shift_n = 23

racc_token_table = {
  false => 0,
  :error => 1,
  :GROUP => 2,
  :REQUIREMENT => 3,
  :TEXT => 4,
  :ROW => 5,
  :CELL => 6 }

racc_nt_base = 7

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "GROUP",
  "REQUIREMENT",
  "TEXT",
  "ROW",
  "CELL",
  "$start",
  "Root",
  "Groups",
  "Requirements",
  "RequirementBody",
  "Text",
  "Table",
  "Rows",
  "Cells" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'parser.y', 10)
  def _reduce_1(val, _values, result)
     result = RootNode.new 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 11)
  def _reduce_2(val, _values, result)
     result = RootNode.new('', val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 15)
  def _reduce_3(val, _values, result)
     result = [ GroupNode.new(val[0]) ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 16)
  def _reduce_4(val, _values, result)
     result = [ GroupNode.new(val[0]) ] + val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 17)
  def _reduce_5(val, _values, result)
     result = [ GroupNode.new(val[0], val[1]) ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 18)
  def _reduce_6(val, _values, result)
     result = [ GroupNode.new(val[0], val[1]) ] + val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 22)
  def _reduce_7(val, _values, result)
     result = [ RequirementNode.new(val[0]) ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 23)
  def _reduce_8(val, _values, result)
     result = [ RequirementNode.new(val[0], val[1]) ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 24)
  def _reduce_9(val, _values, result)
     result = [ RequirementNode.new(val[0], val[1]) ] + val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 28)
  def _reduce_10(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 29)
  def _reduce_11(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 30)
  def _reduce_12(val, _values, result)
     result = val[0] + val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 31)
  def _reduce_13(val, _values, result)
     result = val[0] + val[1] + val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 35)
  def _reduce_14(val, _values, result)
     result = [] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 39)
  def _reduce_15(val, _values, result)
     result = [ ExamplesNode.new('', val[0]) ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 43)
  def _reduce_16(val, _values, result)
     result = [ RowNode.new('', val[1]) ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 44)
  def _reduce_17(val, _values, result)
     result = [ RowNode.new('', val[1]) ] + val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 48)
  def _reduce_18(val, _values, result)
     result = [ val[0] ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 49)
  def _reduce_19(val, _values, result)
     result = [ val[0] ] + val[1] 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
  end   # module BaSpeak
